
server:
  port: 8080
#spring:
#  application:
#    name: springboot-admin-server
#  security:
#    user:
#      password: "123456"
#      name: "admin"
spring:
  boot:
    admin:
      notify:
        mail:
          from: 2457081614@qq.com
          to: 1933837017@qq.com
  mail:
    host: smtp.qq.com
    password: dsjcqiflmebfecbc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    username: 2457081614@qq.com

